### ISSUE TITLE
example r script for worldmap plotting

### ISSUE THREAD

**Issue by HedvigS** [glottolog/cookbook#4]
Here's an example of an R-script that I could add to this cookbook repos if you wanted [https://github.com/HedvigS/cookbook/blob/master/recipes/R/Worldmap_plotting.R](https://github.com/HedvigS/cookbook/blob/master/recipes/R/Worldmap_plotting.R). However, before I go ahead and submit a PR I'd like to know:

* how would you like cldf-data to be fetched here? in this script, I pull it from the raw csv files of the web over at glottolog-cldf. I can fetch it by other means if you prefer.
* I can write this up as functions with arguments instead of as scripts where you can adjust variables, and store the functions in another file and call on it in an example script to showcase how it works. Would you prefer that?

**Comment by xrotwang** [comment]
If you wanted to do it the CLDF way, you'd first fetch the metadata file and infer the filenames of the CSV files from there. But I think  for a Glottolog recipe, it's fine as it is. 

Functions would only make sense if this was a package that people could install, I think. But here, the typical usage would rather be "copy and adapt", I guess.

**Comment by HedvigS** [comment]
It's not hard to read in[ the json file]((https://raw.githubusercontent.com/glottolog/glottolog-cldf/master/cldf/cldf-metadata.json")) and extract things, it's just I'm not sure how that json is constructed and if it'll change in future.

Functions make perfect sense in R outside of packages as well, in fact that's quite common (we do it in grambank-cldf for example). The usage then is to just make it smoother what bits are determined by the user.

Tell you what, I could just ask other R users in the department what they prefer? Maybe that's more in line with this entire enterprise anyway, if we are to make people there more likely to use cldf data?

**Comment by xrotwang** [comment]
I think https://github.com/HedvigS/cookbook/blob/master/recipes/R/Worldmap_plotting.R is doing too much for a simple recipe. The 70 lines here https://github.com/HedvigS/Glottolog_look_up_table/blob/master/Worldmap_plotting.R seem better suited, I'd say. For me, the take away message of such a recipe would be
- here's how you suck the Glottolog language data into R
- here's how to filter for the language level languoids
- here's where the geo coordinates are
- voila: map

**Comment by xrotwang** [comment]
Oh and regarding the stability of the JSON metadata: It's actually the other way round! The JSON is specified by CLDF (and CSVW), so it's the thing that's guaranteed to stay as it is. The filenames otoh may change - or the CSV dialect used.

**Comment by HedvigS** [comment]
Hum.. okay. I really prefer this extended way where there's more information on what to do if you've got an ordered vector or not and the adjustments I made for other options, and for piping in other cldf datasets besides glottolog.

**Comment by HedvigS** [comment]
So I can expect that tables[1] and tables[4] correspond to "values" and "languages"?

**Comment by xrotwang** [comment]
No, you can expect that the table with property [`"dc:conformsTo" = "http://cldf.clld.org/v1.0/terms.rdf#ValueTable"`](https://github.com/glottolog/glottolog-cldf/blob/41c7327b49099352fc9f71d26f8cc8133ea6500f/cldf/cldf-metadata.json#L25) is the `ValueTable`.

**Comment by HedvigS** [comment]
and what happens when cldf v2.0 is released?

**Comment by xrotwang** [comment]
Then things may change. CLDF v1.1 otoh is going to be backwards compatible.

**Comment by HedvigS** [comment]
right, so matching to `"http://cldf.clld.org/.*#ValueTable"` is better then?

**Comment by xrotwang** [comment]
No. The full term URIs are better. We only have these at the moment. And if v1.1 adds new terms, the old ones will still be there.

**Comment by HedvigS** [comment]
Okay, that makes me not want to pull the filenames from the json then.

**Comment by xrotwang** [comment]
Why is that?

**Comment by HedvigS** [comment]
because I want to be able to evaluate the test for where in the json I'm finding things in the future as well.

**Comment by xrotwang** [comment]
And I'm telling you that looking for the table with the exact term URI is going to be more stable than relying on the filename being "values.csv". But as I said above: For a simple recipe that's made for a particular CLDF dataset, sucking in the data from the CSV file directly is ok. For anything generic, one should use rcldf (or similar) anyway.

**Comment by xrotwang** [comment]
Not coding to a spec because there might be an incompatible version of the spec in the future seems a bit absurd, though.

**Comment by xrotwang** [comment]
Just for some context: The way a library like `pycldf` or rcldf would handle new versions of the CLDF spec is by checking the `dc:conformsTo` property of the dataset (see https://github.com/glottolog/glottolog-cldf/blob/41c7327b49099352fc9f71d26f8cc8133ea6500f/cldf/cldf-metadata.json#L25), infer the spec version from it, and then look up the corresponding ontology/terms. So in the best case, such a library would handle multiple versions of the spec transparently.

But just as you can get by reading namespaced XML with a namespace unaware XML parser, you can get by accessing CLDF data by CSV filename. You just have to be aware that you are relying on undefined behaviour. So if things break, you only have yourself to blame.

**Comment by HedvigS** [comment]
Okay. I am trying you know, and I'm asking questions so that I can adapt and improve. I asked if that specific string wouldn't cause it to break in future with newer versions and what I felt I got was "that's still better than relying on filenames (which I've never seen change but versions I have seen change)". That all may make perfect sense to you, but it doesn't to me (yet) and what you're saying and the documentation I'm reading isn't helping me much making more sense of it.

This isn't really feeling great or that this is a welcoming space to submit things. I'll just make some minor tweaks to some scripts I have in the pipeline and then try to just avoid having any more in-depth interactions over this. I want my code to be good (which is why for example I read in the json file in other scripts and outputted a statement on the precise version used etc) but this doesn't really feel like a sustainable way of improving my coding abilities or understanding of cldf. I'm going to try and disengage here, except for the minimum required to submit some scripts I think are at least somewhat useful to other people in our department.

**Comment by xrotwang** [comment]
I'm sorry if my comments came across as offensive. When I said "you can get by" what I meant actually was that accessing CSV files by name is a workable solution - you just have to be aware of the trade-off (gaining simplicity, losing stability).
So "you only have yourself to blame" in this context means, that if things break, it's not the fault of the CLDF spec, but due to non-conformant data reading.

And yes, looking for exact term URIs in the metadata **is** better than relying on filenames (from the point of view of the CLDF spec). The promise of the Glottolog CLDF dataset is that it will always be valid CLDF. Since the spec says that ["a dataset may use non-standard filenames"](https://github.com/cldf/cldf#extended-conformance), switching the name for the ValueTable to `data.csv` (or `data.tsv`, etc.) would be perfectly compatible with that promise (and conformant CLDF readers will make this change invisible for the user). Of course that extends to column names and CSV dialect specification, so reading CLDF data in a fully compliant way may in fact incur quite an overhead (which is why I'm advocating using a dedicated package for this).

Regarding stability of the specification, I think "versions I have seen change" is a bit of a red herring. CLDF is a standard and not a R or python package. For standards, rapid development is never a design goal. So stability is not only in the interest of the user but also of the developer. XML may be a suitable comparison: XML 1.0 was introduced in 1998, and [XML 1.1 was published in 2006](https://www.w3.org/TR/2006/REC-xml11-20060816/#sec-xml11) - and most XML processing software will still happily work with 1.0 docs.

I made [a note](https://github.com/cldf/cldf/issues/104) about the relation between a CLDF component and the `dc:conformsTo` property in the metadata file not being very explicit in the spec.

**Comment by HedvigS** [comment]
It's not offensive, it's just I don't feel particularly encouraged or welcome to submit things or find out things by these discussions. It feels like I'm just a bother and not smart enough to engage with this so I'd rather disengage and just write what makes sense to me and give up on any more complicated interactions with cldf. I still really like cldf and Glottolog and would like to use it myself in a smart way and help others use it, but I'm feeling like I need to cap how engaged I am because these back and forths don't seem to work.

I completely understand why hard-coding the path to a particular sheet may break in future and I'd have myself to blame, this is why I started this thread in the first place asking what the preferred other solution was.

I still don't understand why asterisking out the version number in "`http://cldf.clld.org/v1.0/terms.rdf#ValueTable"` doesn't make sense. It seems like even if future tables are backwards compatible to previous standards, it'd be best to check that the most recent table I can access fits the most recent standard that exists. I also don't know if future jsons for future clef-datasets will have more than one item after  "dc:conformsTo" if it is backwards compatible with more than 1 standard.

I'll just continue doing something less good until I can use rcldf. That seems easiest.
